version: 2

multi-ecosystem-groups:
  playwright:
    schedule:
      interval: weekly
      day: tuesday
      time: "07:00"
    commit-message:
      prefix: "TRIVIAL "

updates:
- package-ecosystem: github-actions
  directories:
    - "/"
    - ".github/actions/*"
  schedule:
    interval: weekly
    day: tuesday
    time: "07:00"
  commit-message:
    prefix: "TRIVIAL "
- package-ecosystem: npm
  directory: "/"
  patterns:
  - "@playwright*"
  multi-ecosystem-group: "playwright"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: "07:00"
  ignore:
  - dependency-name: "@playwright*"
  groups:
    other-dependencies:
      patterns:
      - "*"
  commit-message:
    prefix: "TRIVIAL "
- package-ecosystem: docker
  directory: "/"
  patterns:
  - "playwright"
  multi-ecosystem-group: "playwright"
