name: Notify Tests results
description: Notifies Tests results through Slack

inputs:
  passed:
    description: Number of passed tests
    required: true
  flaky:
    description: Number of flaky tests
    required: true
  failed:
    description: Number of failed tests
    required: true
  skipped:
    description: Number of skipped tests
    required: true
  durationMs:
    description: Duration of the tests in milliseconds
    required: true
  result:
    description: The result of tests
    required: true
  rp_link:
    description: Link to the report portal launch
    required: true
  bg_color:
    description: The background color of the message
    required: true
  slack_channel:
    description: The Slack channel where message is posted
    required: true
  slack_token:
    description: The Slack app token to use
    required: true
  environment:
    description: The environment where the tests were run
    required: true

runs:
  using: composite
  steps:
  - shell: sh
    run: |
      DURATION_MS="${{ inputs.durationMs }}"
      INT_MS=${DURATION_MS%.*}
      if ! echo "$INT_MS" | grep -Eq '^[0-9]+$'; then
        echo "Error: DURATION_MS is not a valid number: $DURATION_MS"
        exit 1
      fi
      MINUTES=$((INT_MS / 60000))
      SECONDS=$(((INT_MS % 60000) / 1000))
      MILLIS=$((INT_MS % 1000))
      FORMATTED_DURATION="${MINUTES}m ${SECONDS}s ${MILLIS}ms"
      echo "FORMATTED_DURATION=$FORMATTED_DURATION" >> "$GITHUB_ENV"
      echo "WORKFLOW_RUN_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> "$GITHUB_ENV"
  - name: Post to a Slack channel
    uses: slackapi/slack-github-action@v2
    with:
      token: ${{ inputs.slack_token }}
      method: chat.postMessage
      payload: |
        {
          "channel": "${{ inputs.slack_channel }}",
          "attachments": [
            {
              "color": "${{ inputs.bg_color}}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Blueprint Tests* has finished"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Environment:* ${{ inputs.environment }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Result:* ${{ inputs.result }} within ${{ env.FORMATTED_DURATION }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Passed:* ${{ inputs.passed }} (+ ${{ inputs.flaky }} flaky)"
                  }
                },
                 {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Failed:* ${{ inputs.failed }}"
                  }
                },
                 {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Skipped:* ${{ inputs.skipped }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Link to tests: <${{ env.WORKFLOW_RUN_URL }}|Workflow run>"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ inputs.rp_link }}|Reportportal launch>"
                  }
                }
              ]
            }
          ]
        }
