name: Playwright Tests - ALME
on:
  workflow_dispatch:
    inputs:
      jamfProBaseUrl:
        description: 'URL of the Jamf Pro server'
        type: string
jobs:
  run-playwright:
    uses: ./.github/workflows/reusable-playwright-setup.yml
    with:
      run-name: 'ALME Stage'
      filter: '@stage'
      jamfProBaseUrl: ${{ github.event.inputs.jamfProBaseUrl || '' }}
      sboxBaseUrl: ''
      slack_channel: 'mercury-alerts'
      notify_success: 'false'
      notify_failure: 'false'
      test_folder: 'app-lifecycle-management'
      rp_project: ''
      rp_attributes: ''
    secrets:
      JAMF_ACCOUNT_STAGE_USER_MAIL: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_MAIL }}
      JAMF_ACCOUNT_STAGE_USER_PASSWORD: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_PASSWORD }}
      JAMF_PRO_STAGE_API_USERNAME: ${{ secrets.JAMF_PRO_STAGE_API_USERNAME }}
      JAMF_PRO_STAGE_API_PASSWORD: ${{ secrets.JAMF_PRO_STAGE_API_PASSWORD }}
      JAMF_SCHOOL_STAGE_API_USERNAME: ${{ secrets.JAMF_SCHOOL_STAGE_API_USERNAME }}
      JAMF_SCHOOL_STAGE_API_PASSWORD: ${{ secrets.JAMF_SCHOOL_STAGE_API_PASSWORD }}
      RP_API_KEY: ${{ secrets.RP_API_KEY }}
      GH_SLACK_TOKEN: ${{ secrets.GH_SLACK_TOKEN }}
