name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
  - cron: "0 6 * * *"
  workflow_dispatch:
    inputs:
      filter:
        description: 'Filter selecting which tests to run'
        type: string
      jamfProBaseUrl:
        description: 'URL of the Jamf Pro server'
        type: string
      sboxBaseUrl:
        description: 'URL of the Blueprints standalone deployment'
        type: string
      slack_channel:
        description: 'Slack channel for notifications'
        required: true
        default: 'ocean-tests'
        type: string
      notify_success:
        description: 'Set to true to notify test channel on success'
        default: 'true'
        type: string
      notify_failure:
        description: 'Set to true to notify test channel on failure'
        default: 'true'
        type: string
      test_folder:
        description: 'Select which folder to run tests from'
        default: 'core-blueprints'
        type: string

jobs:
  setup-playwright-workflow:
    uses: ./.github/workflows/reusable-playwright-setup.yml
    with:
      filter: ${{ github.event.inputs.filter || '' }}
      jamfProBaseUrl: ${{ github.event.inputs.jamfProBaseUrl || '' }}
      sboxBaseUrl: ${{ github.event.inputs.sboxBaseUrl || '' }}
      slack_channel: ${{ github.event.inputs.slack_channel || 'ocean-tests' }}
      notify_success: ${{ github.event.inputs.notify_success || 'true' }}
      notify_failure: ${{ github.event.inputs.notify_failure || 'true' }}
      test_folder: ${{ github.event.inputs.test_folder || 'core-blueprints' }}
    secrets:
      JAMF_ACCOUNT_STAGE_USER_MAIL: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_MAIL }}
      JAMF_ACCOUNT_STAGE_USER_PASSWORD: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_PASSWORD }}
      JAMF_PRO_STAGE_API_USERNAME: ${{ secrets.JAMF_PRO_STAGE_API_USERNAME }}
      JAMF_PRO_STAGE_API_PASSWORD: ${{ secrets.JAMF_PRO_STAGE_API_PASSWORD }}
      JAMF_SCHOOL_STAGE_API_USERNAME: ${{ secrets.JAMF_SCHOOL_STAGE_API_USERNAME }}
      JAMF_SCHOOL_STAGE_API_PASSWORD: ${{ secrets.JAMF_SCHOOL_STAGE_API_PASSWORD }}
      RP_API_KEY: ${{ secrets.RP_API_KEY }}
      GH_SLACK_TOKEN: ${{ secrets.GH_SLACK_TOKEN }}