name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
    inputs:
      filter:
        description: 'Filter selecting which tests to run'
        type: string
      jamfProBaseUrl:
        description: 'URL of the Jamf Pro server'
        type: string
      sboxBaseUrl:
        description: 'URL of the Blueprints standalone deployment'
        type: string


env:
  JAMF_ACCOUNT_STAGE_USER_MAIL: ${{secrets.JAMF_ACCOUNT_STAGE_USER_MAIL}}
  JAMF_ACCOUNT_STAGE_USER_PASSWORD: ${{secrets.JAMF_ACCOUNT_STAGE_USER_PASSWORD}}
  RP_API_KEY: ${{secrets.RP_API_KEY}}
  JAMF_PRO_BASE_URL: ${{ inputs.jamfProBaseUrl }}
  SBOX_BASE_URL: ${{ inputs.sboxBaseUrl }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    container:
      image: mcr.microsoft.com/playwright:v1.49.1
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set Directory as Safe
      run: |
        git config --system --add safe.directory "$GITHUB_WORKSPACE"
      shell: bash
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        cache: 'pnpm'
        node-version-file: '.nvmrc'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
    - name: Run Playwright tests
      run: |
        HOME=/root PLAYWRIGHT_JSON_OUTPUT_NAME=results.json pnpm exec playwright test ${{ github.event.inputs.filter && format('-g {0}', github.event.inputs.filter) || '' }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: results.json
        path: results.json
        retention-days: 30

  extract-results:
    name: Extract test result numbers
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    needs: [ test ]
    if: ${{ !cancelled() }}
    outputs:
      passed: ${{ steps.extract.outputs.PASSED }}
      failed: ${{ steps.extract.outputs.FAILED }}
      skipped: ${{ steps.extract.outputs.SKIPPED }}
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: results.json
    - id: extract
      name: Extract Playwright Test Results
      run: |
        PASSED=$(jq -r '.stats.expected' results.json)
        FAILED=$(jq -r '.stats.unexpected' results.json)
        SKIPPED=$(jq -r '.stats.skipped' results.json)
        echo "PASSED=$PASSED" >> $GITHUB_OUTPUT
        echo "FAILED=$FAILED" >> $GITHUB_OUTPUT
        echo "SKIPPED=$SKIPPED" >> $GITHUB_OUTPUT

  notify-success:
    name: Notify Tests Success
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    needs: [ test, extract-results ]
    if: ${{ success() && github.event_name == 'workflow_dispatch' && needs.extract-results.outputs.passed > 0 }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/notify-result
        with:
          passed: ${{ needs.extract-results.outputs.passed }}
          failed: ${{ needs.extract-results.outputs.failed }}
          skipped: ${{ needs.extract-results.outputs.skipped }}
          result: 'PASSED'
          bg_color: '#36a64f'
          slack_token: ${{ secrets.GH_SLACK_TOKEN }}

  notify-failure:
    name: Notify Tests Failure
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    needs: [ test, extract-results  ]
    if: ${{ (failure() || needs.extract-results.outputs.passed == 0) && github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/notify-result
        with:
          passed: ${{ needs.extract-results.outputs.passed }}
          failed: ${{ needs.extract-results.outputs.failed }}
          skipped: ${{ needs.extract-results.outputs.skipped }}
          result: 'FAILED'
          bg_color: '#FF0000'
          slack_token: ${{ secrets.GH_SLACK_TOKEN }}
