name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
  - cron: "0 6 * * *"
  workflow_dispatch:
    inputs:
      filter:
        description: 'Filter selecting which tests to run'
        type: string
      jamfProBaseUrl:
        description: 'URL of the Jamf Pro server'
        type: string
      sboxBaseUrl:
        description: 'URL of the Blueprints standalone deployment'
        type: string

env:
  JAMF_ACCOUNT_STAGE_USER_MAIL: ${{secrets.JAMF_ACCOUNT_STAGE_USER_MAIL}}
  JAMF_ACCOUNT_STAGE_USER_PASSWORD: ${{secrets.JAMF_ACCOUNT_STAGE_USER_PASSWORD}}
  JAMF_PRO_STAGE_API_USERNAME: ${{secrets.JAMF_PRO_STAGE_API_USERNAME}}
  JAMF_PRO_STAGE_API_PASSWORD: ${{secrets.JAMF_PRO_STAGE_API_PASSWORD}}
  JAMF_SCHOOL_STAGE_API_USERNAME: ${{secrets.JAMF_SCHOOL_STAGE_API_USERNAME}}
  JAMF_SCHOOL_STAGE_API_PASSWORD: ${{secrets.JAMF_SCHOOL_STAGE_API_PASSWORD}}
  RP_API_KEY: ${{secrets.RP_API_KEY}}
  JAMF_PRO_BASE_URL: ${{ inputs.jamfProBaseUrl }}
  SBOX_BASE_URL: ${{ inputs.sboxBaseUrl }}

jobs:
  playwright-version:
    name: Get Playwright version from devDependencies of package.json
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    outputs:
      playwright_version: ${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v4
    - name: Check Playwright version
      id: playwright-version
      run: |
          PLAYWRIGHT_VERSION=$(jq -r '.devDependencies."@playwright/test"' package.json)
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT
      shell: bash
  test:
    timeout-minutes: 60
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    needs: [ playwright-version ]
    container:
      image: mcr.microsoft.com/playwright:v${{ needs.playwright-version.outputs.playwright_version }}
    outputs:
      reportportal_url: ${{ steps.playwright_link.outputs.REPORTPORTAL_URL }}
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v4
    - name: Set Directory as Safe
      run: |
        git config --system --add safe.directory "$GITHUB_WORKSPACE"
      shell: bash
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        cache: 'pnpm'
        node-version-file: '.nvmrc'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
    - id: tests
      name: Run Playwright tests
      run: |
        set -o pipefail
        (HOME=/root PLAYWRIGHT_JSON_OUTPUT_NAME=results.json pnpm exec playwright test tests/smoke-goldminers-jpro.stage.spec.ts)
      shell: bash
    - id: playwright_link
      name: Get Playwright ReportPortal link
      if: always()
      run: |
        REPORTPORTAL_URL=$(grep "^.*ReportPortal Launch Link:" /tmp/playwright.out | grep -o "https.*")
        echo "Reportportal launch: ${REPORTPORTAL_URL}" >> $GITHUB_STEP_SUMMARY
        echo "REPORTPORTAL_URL=$REPORTPORTAL_URL" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: results.json
        path: results.json
        retention-days: 30

  extract-environment:
    name: Extract Environment
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    outputs:
      environment: ${{ steps.extract-env.outputs.environment }}
    steps:
    - id: extract-env
      name: Extract Environment from Filter
      run: |
        if [[ "${{ github.event.inputs.filter }}" == *"stage"* ]]; then
          echo "environment=stage" >> $GITHUB_OUTPUT
        elif [[ "${{ github.event.inputs.filter }}" == *"sbox"* ]]; then
          echo "environment=sbox" >> $GITHUB_OUTPUT
        else
          echo "environment=other" >> $GITHUB_OUTPUT
        fi
      shell: bash

  extract-results:
    name: Extract test result numbers
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    needs: [ test ]
    if: ${{ !cancelled() }}
    outputs:
      passed: ${{ steps.extract.outputs.PASSED }}
      flaky: ${{ steps.extract.outputs.FLAKY }}
      failed: ${{ steps.extract.outputs.FAILED }}
      skipped: ${{ steps.extract.outputs.SKIPPED }}
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: results.json
    - id: extract
      name: Extract Playwright Test Results
      run: |
        PASSED=$(jq -r '.stats.expected' results.json)
        FLAKY=$(jq -r '.stats.flaky' results.json)
        FAILED=$(jq -r '.stats.unexpected' results.json)
        SKIPPED=$(jq -r '.stats.skipped' results.json)
        echo "PASSED=$PASSED" >> $GITHUB_OUTPUT
        echo "FLAKY=$FLAKY" >> $GITHUB_OUTPUT
        echo "FAILED=$FAILED" >> $GITHUB_OUTPUT
        echo "SKIPPED=$SKIPPED" >> $GITHUB_OUTPUT

  notify-success:
    name: Notify Tests Success
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    needs: [ test, extract-results, extract-environment ]
    if: ${{ success() && (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && needs.extract-results.outputs.passed > 0 }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/notify-result
        with:
          passed: ${{ needs.extract-results.outputs.passed }}
          flaky: ${{ needs.extract-results.outputs.flaky }}
          failed: ${{ needs.extract-results.outputs.failed }}
          skipped: ${{ needs.extract-results.outputs.skipped }}
          result: 'PASSED'
          rp_link: ${{ needs.test.outputs.reportportal_url }}
          bg_color: '#36a64f'
          slack_token: ${{ secrets.GH_SLACK_TOKEN }}
          environment: ${{ needs.extract-environment.outputs.environment }}

  notify-failure:
    name: Notify Tests Failure
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    needs: [ test, extract-results, extract-environment ]
    if: ${{ (failure() || needs.extract-results.outputs.passed == 0) && (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/notify-result
        with:
          passed: ${{ needs.extract-results.outputs.passed }}
          flaky: ${{ needs.extract-results.outputs.flaky }}
          failed: ${{ needs.extract-results.outputs.failed }}
          skipped: ${{ needs.extract-results.outputs.skipped }}
          result: 'FAILED'
          rp_link: ${{ needs.test.outputs.reportportal_url }}
          bg_color: '#FF0000'
          slack_token: ${{ secrets.GH_SLACK_TOKEN }}
          environment: ${{ needs.extract-environment.outputs.environment }}


  notify-gm-test-failures:
      name: Notify GM Test Failures
      runs-on: [ self-hosted, jamf-ubuntu-latest ]
      needs: [ test ]
      if: ${{ failure() }}
      env:
        GH_TOKEN: ${{ github.token }}
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: results.json
        - id: extract
          name: Extract Playwright Test Results
          run: |
            if ! [ -f results.json ]; then
              echo "results.json not found"
              exit 1
            fi
  
            has_failure=$(jq -r '
            .suites[]
            | select(.title | test("goldminers"; "i"))
            | .specs[]
            | select(.ok == false)
            | .title
            ' results.json)
  
            if [ -n "$has_failure" ]; then
              echo "Found failing specs in 'goldminers' suite:"
              echo "$has_failure"
              exit 1
            else
              echo "No failed specs found in 'goldminers' suites."
            fi
        - name: Post to Slack on Failure
          if: failure()
          uses: slackapi/slack-github-action@v2.0.0
          with:
            method: chat.postMessage
            token: ${{ secrets.GH_GM_SLACK_TOKEN }}
            payload: |
              channel: "gm-channel-test"
              text: "Blueprints e2e tests: ${{ job.status }}\n"
              blocks:
                - type: "section"
                  text:
                    type: "mrkdwn"
                    text: ":x: Build failed for *Blueprints e2e tests workflow* on branch `${{ github.ref_name }}`: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
