name: PR checks

on:
  pull_request:

jobs:
  lint:
    runs-on: [self-hosted, jamf-ubuntu-latest]
    name: Lint files
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile

    - name: Check formatting
      shell: bash
      run: |
        pnpm lint

  format:
    runs-on: [self-hosted, jamf-ubuntu-latest]
    name: Check formatting
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        shell: bash
        run: |
          pnpm install --frozen-lockfile

      - name: Check formatting
        shell: bash
        run: |
          pnpm format:check
  type-check:
    runs-on: [self-hosted, jamf-ubuntu-latest]
    name: Type check
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile

    - name: Check types
      shell: bash
      run: |
        pnpm tsc:check   

