name: Reusable Playwright setup

on:
  workflow_call:
    inputs:
      run-name:
        description: 'Name of the workflow run'
        required: true
        type: string
      filter:
        description: 'Filter selecting which tests to run'
        required: false
        type: string
      jamfProBaseUrl:
        description: 'URL of the Jamf Pro server'
        required: false
        type: string
      sboxBaseUrl:
        description: 'URL of the Blueprints standalone deployment'
        required: false
        type: string
      slack_channel:
        description: 'Slack channel for notifications'
        required: true
        type: string
      notify_success:
        description: 'Set to true to notify on success'
        required: false
        type: string
      notify_failure:
        description: 'Set to true to notify on failure'
        required: false
        type: string
      test_folder:
        description: 'Select which folder to run tests from'
        required: false
        type: string
      rp_project:
        description: 'ReportPortal project name'
        required: false
        type: string
      rp_attributes:
        description: 'ReportPortal launch attributes'
        required: false
        type: string

    secrets:
      JAMF_ACCOUNT_STAGE_USER_MAIL:
        required: true
      JAMF_ACCOUNT_STAGE_USER_PASSWORD:
        required: true
      JAMF_PRO_STAGE_API_USERNAME:
        required: true
      JAMF_PRO_STAGE_API_PASSWORD:
        required: true
      JAMF_SCHOOL_STAGE_API_USERNAME:
        required: true
      JAMF_SCHOOL_STAGE_API_PASSWORD:
        required: true
      RP_API_KEY:
        required: true
      GH_SLACK_TOKEN:
        required: true

env:
  JAMF_PRO_CUSTOM_BASE_URL: ${{ inputs.jamfProBaseUrl }}
  JAMF_PRO_CUSTOM_ACCOUNT_EMAIL: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_MAIL }}
  JAMF_PRO_CUSTOM_ACCOUNT_PASSWORD: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_PASSWORD }}
  JAMF_PRO_CUSTOM_API_USERNAME: ${{ secrets.JAMF_PRO_STAGE_API_USERNAME }}
  JAMF_PRO_CUSTOM_API_PASSWORD: ${{ secrets.JAMF_PRO_STAGE_API_PASSWORD }}

  STANDALONE_SBOX_BASE_URL: ${{ inputs.sboxBaseUrl || 'https://blueprints.sbox-mfe.jamf.io' }}

  JAMF_SCHOOL_STAGE_BASE_URL: ${{ vars.JAMF_SCHOOL_STAGE_BASE_URL }}
  JAMF_SCHOOL_STAGE_ACCOUNT_EMAIL: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_MAIL }}
  JAMF_SCHOOL_STAGE_ACCOUNT_PASSWORD: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_PASSWORD }}
  JAMF_SCHOOL_STAGE_API_USERNAME: ${{ secrets.JAMF_SCHOOL_STAGE_API_USERNAME }}
  JAMF_SCHOOL_STAGE_API_PASSWORD: ${{ secrets.JAMF_SCHOOL_STAGE_API_PASSWORD }}

  JAMF_PRO_DEVELOP_STAGE_BASE_URL: ${{ vars.JAMF_PRO_DEVELOP_STAGE_BASE_URL }}
  JAMF_PRO_DEVELOP_STAGE_ACCOUNT_EMAIL: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_MAIL }}
  JAMF_PRO_DEVELOP_STAGE_ACCOUNT_PASSWORD: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_PASSWORD }}
  JAMF_PRO_DEVELOP_STAGE_API_USERNAME: ${{ secrets.JAMF_PRO_STAGE_API_USERNAME }}
  JAMF_PRO_DEVELOP_STAGE_API_PASSWORD: ${{ secrets.JAMF_PRO_STAGE_API_PASSWORD }}

  JAMF_PRO_RC_STAGE_BASE_URL: ${{ vars.JAMF_PRO_RC_STAGE_BASE_URL }}
  JAMF_PRO_RC_STAGE_ACCOUNT_EMAIL: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_MAIL }}
  JAMF_PRO_RC_STAGE_ACCOUNT_PASSWORD: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_PASSWORD }}
  JAMF_PRO_RC_STAGE_API_USERNAME: ${{ secrets.JAMF_PRO_STAGE_API_USERNAME }}
  JAMF_PRO_RC_STAGE_API_PASSWORD: ${{ secrets.JAMF_PRO_STAGE_API_PASSWORD }}

  JAMF_PRO_GA_STAGE_BASE_URL: ${{ vars.JAMF_PRO_GA_STAGE_BASE_URL }}
  JAMF_PRO_GA_STAGE_ACCOUNT_EMAIL: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_MAIL }}
  JAMF_PRO_GA_STAGE_ACCOUNT_PASSWORD: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_PASSWORD }}
  JAMF_PRO_GA_STAGE_API_USERNAME: ${{ secrets.JAMF_PRO_STAGE_API_USERNAME }}
  JAMF_PRO_GA_STAGE_API_PASSWORD: ${{ secrets.JAMF_PRO_STAGE_API_PASSWORD }}

  JAMF_PRO_GA_1_STAGE_BASE_URL: ${{ vars.JAMF_PRO_GA_1_STAGE_BASE_URL }}
  JAMF_PRO_GA_1_STAGE_ACCOUNT_EMAIL: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_MAIL }}
  JAMF_PRO_GA_1_STAGE_ACCOUNT_PASSWORD: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_PASSWORD }}
  JAMF_PRO_GA_1_STAGE_API_USERNAME: ${{ secrets.JAMF_PRO_STAGE_API_USERNAME }}
  JAMF_PRO_GA_1_STAGE_API_PASSWORD: ${{ secrets.JAMF_PRO_STAGE_API_PASSWORD }}

  JAMF_PRO_GA_2_STAGE_BASE_URL: ${{ vars.JAMF_PRO_GA_2_STAGE_BASE_URL }}
  JAMF_PRO_GA_2_STAGE_ACCOUNT_EMAIL: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_MAIL }}
  JAMF_PRO_GA_2_STAGE_ACCOUNT_PASSWORD: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_PASSWORD }}
  JAMF_PRO_GA_2_STAGE_API_USERNAME: ${{ secrets.JAMF_PRO_STAGE_API_USERNAME }}
  JAMF_PRO_GA_2_STAGE_API_PASSWORD: ${{ secrets.JAMF_PRO_STAGE_API_PASSWORD }}

  RP_API_KEY: ${{ secrets.RP_API_KEY }}
  RP_PROJECT: ${{ inputs.rp_project }}
  RP_ATTRIBUTES: ${{ inputs.rp_attributes }}

jobs:
  playwright-version:
    name: Get Playwright version from devDependencies of package.json
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    outputs:
      playwright_version: ${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v6
      - name: Check Playwright version
        id: playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(jq -r '.devDependencies."@playwright/test"' package.json)
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT
        shell: bash
  transform-inputs:
    name: Transform Inputs
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    outputs:
      run_name: ${{ steps.transform.outputs.RUN_NAME }}
    steps:
      - id: transform
        name: Transform Inputs
        run: |
          raw="${{ inputs.run-name }}"
          echo "RUN_NAME=${raw//[[:space:]]/_}" >> $GITHUB_OUTPUT
        shell: bash
  test:
    timeout-minutes: 60
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    needs: [ playwright-version, transform-inputs ]
    container:
      image: mcr.microsoft.com/playwright:v${{ needs.playwright-version.outputs.playwright_version }}
    outputs:
      reportportal_url: ${{ steps.playwright_link.outputs.REPORTPORTAL_URL }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v6
      - name: Set Directory as Safe
        run: |
          git config --system --add safe.directory "$GITHUB_WORKSPACE"
        shell: bash
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash
      - id: tests
        name: Run Playwright tests
        run: |
          set -o pipefail 
          (HOME=/root PLAYWRIGHT_JSON_OUTPUT_NAME=results.json pnpm exec playwright test \
          ${{ inputs.test_folder && format('{0}', inputs.test_folder) || '' }} ${{ inputs.filter && format('-g {0}', inputs.filter) || '' }} 2>&1) | tee /tmp/playwright.out
        shell: bash
      - id: playwright_link
        name: Get Playwright ReportPortal link
        if: always()
        run: |
          REPORTPORTAL_URL=$(grep "^.*ReportPortal Launch Link:" /tmp/playwright.out | grep -o "https.*")
          echo "Reportportal launch: ${REPORTPORTAL_URL}" >> $GITHUB_STEP_SUMMARY
          echo "REPORTPORTAL_URL=$REPORTPORTAL_URL" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/upload-artifact@v6
        if: always()
        with:
          name: ${{ needs.transform-inputs.outputs.run_name }}-playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v6
        if: always()
        with:
          name: ${{ needs.transform-inputs.outputs.run_name }}-results.json
          path: results.json
          retention-days: 30

  extract-environment:
    name: Extract Environment
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    outputs:
      environment: ${{ steps.extract-env.outputs.environment }}
    steps:
      - id: extract-env
        name: Extract Environment from Filter
        run: |
          if [[ "${{ inputs.filter }}" == *"stage"* ]]; then
            echo "environment=stage" >> $GITHUB_OUTPUT
          elif [[ "${{ inputs.filter }}" == *"sbox"* ]]; then
            echo "environment=sbox" >> $GITHUB_OUTPUT
          else
            echo "environment=other" >> $GITHUB_OUTPUT
          fi
        shell: bash

  extract-results:
    name: Extract test result numbers
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    needs: [ test, transform-inputs ]
    if: ${{ !cancelled() }}
    outputs:
      passed: ${{ steps.extract.outputs.PASSED }}
      flaky: ${{ steps.extract.outputs.FLAKY }}
      failed: ${{ steps.extract.outputs.FAILED }}
      skipped: ${{ steps.extract.outputs.SKIPPED }}
      durationMs: ${{ steps.extract.outputs.DURATION_MS }}
    steps:
      - id: download
        name: Download Playwright Test Results Artifact
        uses: actions/download-artifact@v7
        with:
          name: ${{ needs.transform-inputs.outputs.run_name }}-results.json
      - id: extract
        name: Extract Playwright Test Results
        run: |
          PASSED=$(jq -r '.stats.expected' results.json)
          FLAKY=$(jq -r '.stats.flaky' results.json)
          FAILED=$(jq -r '.stats.unexpected' results.json)
          SKIPPED=$(jq -r '.stats.skipped' results.json)
          DURATION_MS=$(jq -r '.stats.duration' results.json)
          echo "PASSED=$PASSED" >> $GITHUB_OUTPUT
          echo "FLAKY=$FLAKY" >> $GITHUB_OUTPUT
          echo "FAILED=$FAILED" >> $GITHUB_OUTPUT
          echo "SKIPPED=$SKIPPED" >> $GITHUB_OUTPUT
          echo "DURATION_MS=$DURATION_MS" >> $GITHUB_OUTPUT

  notify-success:
    name: Notify Tests Success
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    needs: [ test, extract-results, extract-environment ]
    if: ${{ inputs.notify_success == 'true' && success() && (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && needs.extract-results.outputs.passed > 0 }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/notify-result
        with:
          passed: ${{ needs.extract-results.outputs.passed }}
          flaky: ${{ needs.extract-results.outputs.flaky }}
          failed: ${{ needs.extract-results.outputs.failed }}
          skipped: ${{ needs.extract-results.outputs.skipped }}
          durationMs: ${{ needs.extract-results.outputs.durationMs }}
          run_name: ${{ inputs.run-name }}
          result: 'PASSED'
          rp_link: ${{ needs.test.outputs.reportportal_url }}
          bg_color: '#36a64f'
          slack_channel: ${{ inputs.slack_channel }}
          slack_token: ${{ secrets.GH_SLACK_TOKEN }}
          environment: ${{ needs.extract-environment.outputs.environment }}

  notify-failure:
    name: Notify Tests Failure
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    needs: [ test, extract-results, extract-environment ]
    if: ${{ inputs.notify_failure == 'true' && (failure() || needs.extract-results.outputs.passed == 0) && (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/notify-result
        with:
          passed: ${{ needs.extract-results.outputs.passed }}
          flaky: ${{ needs.extract-results.outputs.flaky }}
          failed: ${{ needs.extract-results.outputs.failed }}
          skipped: ${{ needs.extract-results.outputs.skipped }}
          durationMs: ${{ needs.extract-results.outputs.durationMs }}
          run_name: ${{ inputs.run-name }}
          result: 'FAILED'
          rp_link: ${{ needs.test.outputs.reportportal_url }}
          bg_color: '#FF0000'
          slack_channel: ${{ inputs.slack_channel }}
          slack_token: ${{ secrets.GH_SLACK_TOKEN }}
          environment: ${{ needs.extract-environment.outputs.environment }}

  generate-slack-message-links-artifact:
    name: Generate Slack Message Blocks from Links
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    needs: [ test, transform-inputs ]
    if: ${{ !cancelled() }}
    steps:
    - name: Generate Slack Message Blocks from Links
      uses: jamf/github-actions-system-tests/create-slack-links-artifact@v1
      with:
        links: |
          ReportPortal|${{ needs.test.outputs.reportportal_url }}
          Workflow|${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
