name: Playwright Tests

on:
  workflow_call:
    inputs:
      filter:
        description: 'Filter selecting which tests to run'
        required: false
        type: string
      jamfProBaseUrl:
        description: 'URL of the Jamf Pro server'
        required: false
        type: string
      sboxBaseUrl:
        description: 'URL of the Blueprints standalone deployment'
        required: false
        type: string
      slack_channel:
        required: true
        type: string
        description: 'Slack channel for notifications'
      notify_success:
        description: 'Set to true to notify on success'
        required: false
        type: string
    secrets:
      JAMF_ACCOUNT_STAGE_USER_MAIL:
        required: true
      JAMF_ACCOUNT_STAGE_USER_PASSWORD:
        required: true
      JAMF_PRO_STAGE_API_USERNAME:
        required: true
      JAMF_PRO_STAGE_API_PASSWORD:
        required: true
      JAMF_SCHOOL_STAGE_API_USERNAME:
        required: true
      JAMF_SCHOOL_STAGE_API_PASSWORD:
        required: true
      RP_API_KEY:
        required: true
      GH_SLACK_TOKEN:
        required: true
      GH_GM_SLACK_TOKEN:
        required: true

env:
  JAMF_ACCOUNT_STAGE_USER_MAIL: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_MAIL }}
  JAMF_ACCOUNT_STAGE_USER_PASSWORD: ${{ secrets.JAMF_ACCOUNT_STAGE_USER_PASSWORD }}
  JAMF_PRO_STAGE_API_USERNAME: ${{ secrets.JAMF_PRO_STAGE_API_USERNAME }}
  JAMF_PRO_STAGE_API_PASSWORD: ${{ secrets.JAMF_PRO_STAGE_API_PASSWORD }}
  JAMF_SCHOOL_STAGE_API_USERNAME: ${{ secrets.JAMF_SCHOOL_STAGE_API_USERNAME }}
  JAMF_SCHOOL_STAGE_API_PASSWORD: ${{ secrets.JAMF_SCHOOL_STAGE_API_PASSWORD }}
  RP_API_KEY: ${{ secrets.RP_API_KEY }}
  JAMF_PRO_BASE_URL: ${{ inputs.jamfProBaseUrl }}
  SBOX_BASE_URL: ${{ inputs.sboxBaseUrl }}

jobs:
  playwright-version:
    name: Get Playwright version from devDependencies of package.json
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    outputs:
      playwright_version: ${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - id: playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(jq -r '.devDependencies."@playwright/test"' package.json)
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT

  test:
    timeout-minutes: 60
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    needs: [ playwright-version ]
    container:
      image: mcr.microsoft.com/playwright:v${{ needs.playwright-version.outputs.playwright_version }}
    outputs:
      reportportal_url: ${{ steps.playwright_link.outputs.REPORTPORTAL_URL }}
    steps:
      - uses: actions/checkout@v4
      - run: git config --system --add safe.directory "$GITHUB_WORKSPACE"
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'
      - run: pnpm install --frozen-lockfile
      - id: tests
        run: |
          set -o pipefail
          (HOME=/root PLAYWRIGHT_JSON_OUTPUT_NAME=results.json pnpm exec playwright test ${{ inputs.filter && format('-g {0}', inputs.filter) || '' }} 2>&1) | tee /tmp/playwright.out
      - id: playwright_link
        if: always()
        run: |
          REPORTPORTAL_URL=$(grep "^.*ReportPortal Launch Link:" /tmp/playwright.out | grep -o "https.*")
          echo "Reportportal launch: ${REPORTPORTAL_URL}" >> $GITHUB_STEP_SUMMARY
          echo "REPORTPORTAL_URL=$REPORTPORTAL_URL" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: results.json
          path: results.json
          retention-days: 30

  extract-environment:
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    outputs:
      environment: ${{ steps.extract-env.outputs.environment }}
    steps:
      - id: extract-env
        run: |
          if [[ "${{ inputs.filter }}" == *"stage"* ]]; then
            echo "environment=stage" >> $GITHUB_OUTPUT
          elif [[ "${{ inputs.filter }}" == *"sbox"* ]]; then
            echo "environment=sbox" >> $GITHUB_OUTPUT
          else
            echo "environment=other" >> $GITHUB_OUTPUT
          fi

  extract-results:
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    needs: [ test ]
    if: ${{ !cancelled() }}
    outputs:
      passed: ${{ steps.extract.outputs.PASSED }}
      flaky: ${{ steps.extract.outputs.FLAKY }}
      failed: ${{ steps.extract.outputs.FAILED }}
      skipped: ${{ steps.extract.outputs.SKIPPED }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: results.json
      - id: extract
        run: |
          PASSED=$(jq -r '.stats.expected' results.json)
          FLAKY=$(jq -r '.stats.flaky' results.json)
          FAILED=$(jq -r '.stats.unexpected' results.json)
          SKIPPED=$(jq -r '.stats.skipped' results.json)
          echo "PASSED=$PASSED" >> $GITHUB_OUTPUT
          echo "FLAKY=$FLAKY" >> $GITHUB_OUTPUT
          echo "FAILED=$FAILED" >> $GITHUB_OUTPUT
          echo "SKIPPED=$SKIPPED" >> $GITHUB_OUTPUT

  notify-success:
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    needs: [ test, extract-results, extract-environment ]
    if: ${{ inputs.notify_success && success() && needs.extract-results.outputs.passed > 0 }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/notify-result
        with:
          passed: ${{ needs.extract-results.outputs.passed }}
          flaky: ${{ needs.extract-results.outputs.flaky }}
          failed: ${{ needs.extract-results.outputs.failed }}
          skipped: ${{ needs.extract-results.outputs.skipped }}
          result: 'PASSED'
          rp_link: ${{ needs.test.outputs.reportportal_url }}
          bg_color: '#36a64f'
          slack_channel: ${{ inputs.slack_channel }}
          slack_token: ${{ secrets.GH_SLACK_TOKEN }}
          environment: ${{ needs.extract-environment.outputs.environment }}

  notify-failure:
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    needs: [ test, extract-results, extract-environment ]
    if: ${{ (failure() || needs.extract-results.outputs.passed == 0) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/notify-result
        with:
          passed: ${{ needs.extract-results.outputs.passed }}
          flaky: ${{ needs.extract-results.outputs.flaky }}
          failed: ${{ needs.extract-results.outputs.failed }}
          skipped: ${{ needs.extract-results.outputs.skipped }}
          result: 'FAILED'
          rp_link: ${{ needs.test.outputs.reportportal_url }}
          bg_color: '#FF0000'
          slack_channel: ${{ inputs.slack_channel }}
          slack_token: ${{ secrets.GH_SLACK_TOKEN }}
          environment: ${{ needs.extract-environment.outputs.environment }}

  notify-failure-to-gm-channel:
    runs-on: [ self-hosted, jamf-ubuntu-latest ]
    needs: [ test, extract-results ]
    if: ${{ (failure() || needs.extract-results.outputs.passed == 0) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/notify-gm-result
        with:
          artifact_name: results.json
          slack_token: ${{ secrets.GH_GM_SLACK_TOKEN }}
          slack_channel: "gm-tests"